version: '3.8'

services:
  scraper:
    build: .
    container_name: digicel-router-scraper
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DUMP_PATH=/app/data
      - LOG_LEVEL=INFO
      - ROUTER_URL=http://192.168.100.1/html/bbsp/pcp/pcp.asp
      - ROUTER_USERNAME=Digicel
      - ROUTER_PASSWORD=Digicel
      - REFRESH_INTERVAL=300
    restart: unless-stopped
    network_mode: host  # Required to access router on local network