version: '3.8'

services:
  digicel-port-scraper:  # More descriptive service name
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: digicel-port-scraper
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs/digicel  # Separate log directory
      - ./.env:/app/.env
    environment:
      - DUMP_PATH=/app/data
      - LOG_LEVEL=INFO
      - ROUTER_URL=http://192.168.100.1/html/bbsp/pcp/pcp.asp
      - ROUTER_USERNAME=Digicel
      - ROUTER_PASSWORD=Digicel
      - REFRESH_INTERVAL=300
      - CHROME_HEADLESS=true
      - ENABLE_FILE_DUMP=true
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    restart: unless-stopped
    network_mode: host  # Required for router access
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "python", "-c", "import os; os.path.exists('/app/logs/digicel/app.log') and exit(0) or exit(1)"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "digicel-port-scraper"  # Proper labeling for log identification